apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zv9iqws34-go
  janus-idp.io/tekton: zv9iqws34-go
  backstage.io/kubernetes-id: zv9iqws34-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zv9iqws34-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
